language: node_js
node_js: # a good example: https://github.com/pillarjs/router/blob/master/.travis.yml
  # - "0.8"
  # - "0.10"
  # - "0.12"
  # - "1.8"
  # - "2.5"
  # - "3.3"
  # - "4.9"
  # - "5.12"
  # - "6.17"
  # - "7.10"
  # - "8.17"
  # - "9.11"
  - "10"
  # - "11"
  # - "12"
  # - "13"
  # - lts/*
  # - node
sudo: false
cache:
  directories:
    - node_modules
scripts:
  - npm run change:language -- javascript
  - npm i
  - npm run test
  - npm run build
  - git checkout .
  - npm run change:language -- typescript
  - npm run test
  - npm run build
# after_script:
#   - test $TRAVIS_NODE_VERSION == '10' && sonar-scanner
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
# addons:
#   sonarcloud:
#     organization: "organisation"
#     token:
#       secure: "secure"

