version: '3'

tasks:
  publish:
    cmds:
      - |
        echo "//registry.npmjs.org/:_authToken={{ .NPM_TOKEN }}" > ~/.npmrc
        npm run build
        find ./packages -type d -maxdepth 1 -mindepth 1 | while read pkg; do
          if [ -d "$pkg" ]; then
            cd "$pkg"

            latest_published_version=$(npm view $(cat package.json | jq -r '.name') version)
            latest_local_version=$(cat package.json | jq -r '.version')

            if [ "$latest_published_version" != "$latest_local_version" ]; then
              echo "> Publishing $pkg@$latest_local_version"
              npm publish --access public
            fi

            cd -
          else
            echo "> Skipping $pkg; Version $latest_local_version already published"
          fi
        done
    desc: 'Publish all packages'
    summary: |
      Run example:
        task publish NPM_TOKEN=token
    vars:
      NPM_TOKEN: '{{ .NPM_TOKEN | default "none" }}'
